---
- name: Apt update
  apt:
    update_cache: yes

- name: Install package for Docker
  apt:
    name:
      - ca-certificates
      - curl
      - apt-transport-https
      - software-properties-common
      - lsb-release
    state: present
    update_cache: yes    

- name: Add Docker repo key
  shell: |
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/docker.gpg
  args:
    creates: /etc/apt/trusted.gpg.d/docker.gpg

- name: Add Docker repo
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present

- name: Install Docker and compose
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    state: present
    update_cache: yes
  notify:
    - Enable docker
    - Restart docker 
